packages:
  - packages/*
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': false
  '@google/genai': false
  esbuild: false
  koffi: false
  node-pty: false
  protobufjs: false
patchedDependencies:
  '@deepseek-ai/cordis-plugin-hmr@1.0.16': patches/@deepseek-ai__cordis-plugin-hmr@1.0.16.patch
